name: Scheduled Empty Commit

on:
  schedule:
    # Runs at 00:00 UTC every day (Change this cron syntax as needed)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"

      - name: Create and Push Empty Commit
        run: |
          git commit --allow-empty -m "Chore: Scheduled empty commit"
          git push origin main
